site_name: geff

site_url: https://live-image-tracking-tools.github.io/geff/
repo_url: https://github.com/live-image-tracking-tools/geff
repo_name: live-image-tracking-tools/geff

nav:
  - index.md
  - what-is-geff.md
  - specification.md
  - tracking.md
  - command-line-tools.md
  - tips-and-tricks.md
  - compatibility.md
  - convert.md

theme:
  name: "material"
  # logo: images/GEFF_Icon_RGB.png # TODO: currently this doesn't render well -- too small
  # palette:
  #   scheme: slate
  #   primary: purple
  #   accent: purple
  features:
    - navigation.indexes

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - css/extra.css

extra:
  version:
    provider: mike
    default: latest

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - mkdocs-typer
  - pymdownx.arithmatex:
      generic: true


plugins:
- search
- mkdocstrings:
    handlers:
      python:
        inventories:
          - https://docs.python.org/3/objects.inv
          - https://networkx.org/documentation/stable/objects.inv
        options:
          docstring_section_style: table # "list" or "table"
          docstring_style: "google"
          filters: ["!_^"]
          heading_level: 3 
          merge_init_into_class: true
          # parameter_headings: true # makes parameters show up in side TOC
          separate_signature: true
          show_root_heading: true
          show_source: false
          show_signature_annotations: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          # summary: true
          line_length: 60
          show_docstring_attributes: true
          show_attribute_values: true
          show_labels: false
          extensions:
          - griffe_fieldz
- include-markdown
- api-autonav:
    nav_section_title: "Python API"
    modules: ['src/geff']
- autorefs