site_name: geff

site_url: https://live-image-tracking-tools.github.io/geff/
repo_url: https://github.com/live-image-tracking-tools/geff
repo_name: live-image-tracking-tools/geff

nav:
  - index.md
  - what-is-geff.md
  - specification.md
  - command-line-tools.md

theme:
  name: "material"
  # logo: images/GEFF_Icon_RGB.png # TODO: currently this doesn't render well -- too small
  # palette:
  #   scheme: slate
  #   primary: purple
  #   accent: purple

extra_css:
  - css/schema_doc.css
extra_javascript:
  - js/schema_doc.min.js

extra:
  version:
    provider: mike
    default: latest

hooks:
  - docs/_hooks.py

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - mkdocs-typer

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        inventories:
          - https://docs.python.org/3/objects.inv
          - https://networkx.org/documentation/stable/objects.inv
        options:
          docstring_section_style: table # or "table"
          docstring_style: "google"
    #       filters: ["!^_"]
          heading_level: 3 
          merge_init_into_class: true
          # parameter_headings: true # makes parameters show up in side TOC
          separate_signature: true
          show_root_heading: true
          show_source: false
          show_signature_annotations: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          # summary: true
          line_length: 60
- include-markdown
- api-autonav:
    modules: ['src/geff']