site_name: geff

site_url: https://live-image-tracking-tools.github.io/geff/

theme:
  name: "material"
  # palette:
  #   scheme: slate
  #   primary: purple
  #   accent: purple

extra:
  version:
    provider: mike
    default: latest

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        import:
          - https://docs.python.org/3/objects.inv
          - https://networkx.org/documentation/stable/objects.inv
        options:
          docstring_section_style: list # or "table"
          docstring_style: "google"
    #       filters: ["!^_"]
          heading_level: 2 # TODO: for legibility header level 2 looks better, but then conflicts with section headers. 3 looks too small
          merge_init_into_class: true
          # parameter_headings: true
          separate_signature: true
          show_root_heading: true
          show_source: false
          show_signature_annotations: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          # summary: true
- include-markdown